apiVersion: v1
kind: Service
metadata:
  name: aksrg2ss-loadbalancer-service
  labels:
    app: aksrg2ss
spec:
  type: LoadBalancer
  selector:
    app: aksrg2ss
  ports:
    - port: 80
      targetPort: 80
